name: python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: run makefile
        run: make
      - name: check files
        run: ls -lrt
      - name: run myls
        run: ./myls
      - name: run myls -i
        run: ./myls -i
      - name: run myls -R
        run: ./myls -R
      - name: check files 
        if: always()
        run: ls
