name: python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: run makefile
        run: |
          make
      - name: check files
        run: ls -lrt
      - name: run myls
        run: ./myls
      - name: run myls -i
        run: ./myls -i
      - name: run myls -R
        run: ./myls -R
      - name: run myls -iRl
        run: ./myls -iRL
      - name: check files 
        if: always()
        run: ls 
      - name: copy test script to student dir
        if: always()
        run: cp /tmp/testscript/A4.py .
      - name: run test script
        if: always()
        run: python3 A4.py
      - name: remove testscript from student dir
        if: always()
        run: rm -f A4.py
      - name: check grade files
        if: always()
        run: cat Student_grade.txt
