# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: run makefile
        run: |
          make
      - name: check files
        run: ls -lrt
      - name: run myls
        run: ./myls
      - name: run myls -i
        run: ./myls -i
      - name: run myls -R
        run: ./myls -R
      - name: run myls -iRl
        run: ./myls -iRL
      - name: check files 
        if: always()
        run: ls 
      - name: copy test script to student dir
        if: always()
        run: cp /tmp/testscript/A4.py .
      - name: run test script
        if: always()
        run: python3 A4.py
      - name: remove testscript from student dir
        if: always()
        run: rm -f A4.py
      - name: check grade files
        if: always()
        run: cat Student_grade.txt
